{% set build = 0 %}
{% set mpi = (environ.get('MPI') or 'mpich') if not win else 'msmpi' %}
{% set mpi_version = {'mpich':'>=3.2', 'openmpi':'>=1.10'}.get(mpi,'') %}

package:
  name: mpi4py
  version: 2.0.1a0

about:
  home: https://bitbucket.org/mpi4py/
  summary: 'Python bindings for MPI'
  license: 'BSD (https://bitbucket.org/mpi4py/mpi4py/src/master/LICENSE.rst)'

source:
# git_url: https://bitbucket.org/mpi4py/mpi4py
# git_rev: master
  path: ../../../..

requirements:
  build:
    - python
    - cython >=0.22
    - {{mpi}} {{mpi_version}} # [not win]
  run:
    - python
    - {{mpi}} {{mpi_version}} # [not win]

build:
  number: {{build}}
  string: py{{py}}_{{mpi}}_{{build}}
  features:   # [not win]
    - {{mpi}} # [not win]
  script: '$PYTHON  setup.py install' # [not win]
  script: '%PYTHON% setup.py install' # [win]

test:
  imports:
    - mpi4py
    - mpi4py.rc
    - mpi4py.dl # [not win]
    - mpi4py.MPI
